OrdererOrgs:
  - Name: Orderer
    Domain: traffic-network.com
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: Org1
    Domain: org1.traffic-network.com
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.traffic-network.com
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.traffic-network.com
    Template:
      Count: 2
    Users:
      Count: 1
