// ============================================================================
// Reading Contract - Gestion des lectures de capteurs
// Smart City Traffic Management System
// ============================================================================

package chaincode

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

// getOrCreateSensor récupère un capteur ou le crée automatiquement s'il n'existe pas
func (c *SensorDataContract) getOrCreateSensor(ctx contractapi.TransactionContextInterface, sensorID string, sensorType SensorType) (*Sensor, error) {
	sensorJSON, err := ctx.GetStub().GetState(sensorID)
	if err != nil {
		return nil, fmt.Errorf("erreur de lecture du ledger: %v", err)
	}

	// Si le capteur existe, le retourner
	if sensorJSON != nil {
		var sensor Sensor
		err = json.Unmarshal(sensorJSON, &sensor)
		if err != nil {
			return nil, fmt.Errorf("erreur de désérialisation: %v", err)
		}
		return &sensor, nil
	}

	// Créer automatiquement le capteur
	sensor := Sensor{
		DocType:         "sensor",
		ID:              sensorID,
		Name:            fmt.Sprintf("Auto-created %s sensor %s", sensorType, sensorID),
		Type:            sensorType,
		Status:          SensorStatusActive,
		Location:        GeoPoint{Latitude: 33.5731, Longitude: -7.5898},
		RoadID:          "ROAD-001",
		Manufacturer:    "AutoGenerated",
		Model:           "SIM-100",
		FirmwareVersion: "1.0.0",
		InstallDate:     time.Now(),
		LastMaintenance: time.Now(),
		LastReading:     time.Now(),
		BatteryLevel:    100.0,
		SignalStrength:  100.0,
		ReadingInterval: 60,
		CreatedAt:       time.Now(),
		CreatedBy:       "SIMULATOR",
		Organization:    "SimulationNetwork",
	}

	newSensorJSON, err := json.Marshal(sensor)
	if err != nil {
		return nil, fmt.Errorf("erreur de sérialisation: %v", err)
	}

	err = ctx.GetStub().PutState(sensorID, newSensorJSON)
	if err != nil {
		return nil, fmt.Errorf("erreur d'écriture du capteur: %v", err)
	}

	return &sensor, nil
}

// RecordReading enregistre une nouvelle lecture de capteur
func (c *SensorDataContract) RecordReading(ctx contractapi.TransactionContextInterface,
	readingID, sensorID string, dataJSON string, quality string) error {

	// Récupérer ou créer le capteur automatiquement
	sensor, err := c.getOrCreateSensor(ctx, sensorID, SensorTypeTraffic)
	if err != nil {
		return err
	}

	// Vérifier que le capteur est actif
	if sensor.Status != SensorStatusActive {
		return fmt.Errorf("le capteur %s n'est pas actif (statut: %s)", sensorID, sensor.Status)
	}

	// Parser les données
	var data map[string]interface{}
	err = json.Unmarshal([]byte(dataJSON), &data)
	if err != nil {
		return fmt.Errorf("erreur de parsing des données: %v", err)
	}

	// Obtenir l'identité du validateur
	validatedBy, err := ctx.GetClientIdentity().GetID()
	if err != nil {
		validatedBy = "SYSTEM"
	}

	reading := SensorReading{
		DocType:     "sensorReading",
		ID:          readingID,
		SensorID:    sensorID,
		Timestamp:   time.Now(),
		Data:        data,
		Quality:     DataQuality(quality),
		RawValue:    dataJSON,
		ProcessedAt: time.Now(),
		ValidatedBy: validatedBy,
	}

	readingJSON, err := json.Marshal(reading)
	if err != nil {
		return fmt.Errorf("erreur de sérialisation: %v", err)
	}

	// Mettre à jour le timestamp de dernière lecture du capteur
	sensor.LastReading = time.Now()
	sensorJSON, err := json.Marshal(sensor)
	if err == nil {
		ctx.GetStub().PutState(sensorID, sensorJSON)
	}

	return ctx.GetStub().PutState(readingID, readingJSON)
}

// RecordTrafficReading enregistre une lecture de capteur de trafic
func (c *SensorDataContract) RecordTrafficReading(ctx contractapi.TransactionContextInterface,
	readingID, sensorID string, vehicleCount int, averageSpeed float64,
	occupancy float64, flow int, laneNumber int) error {

	// Récupérer ou créer le capteur automatiquement
	sensor, err := c.getOrCreateSensor(ctx, sensorID, SensorTypeTraffic)
	if err != nil {
		return err
	}

	trafficData := TrafficSensorData{
		VehicleCount: vehicleCount,
		AverageSpeed: averageSpeed,
		Occupancy:    occupancy,
		Flow:         flow,
		LaneNumber:   laneNumber,
	}

	data := map[string]interface{}{
		"vehicleCount": trafficData.VehicleCount,
		"averageSpeed": trafficData.AverageSpeed,
		"occupancy":    trafficData.Occupancy,
		"flow":         trafficData.Flow,
		"laneNumber":   trafficData.LaneNumber,
	}

	// Déterminer la qualité des données
	quality := DataQualityHigh
	if vehicleCount < 0 || averageSpeed < 0 || occupancy < 0 || occupancy > 100 {
		quality = DataQualityInvalid
	}

	validatedBy, _ := ctx.GetClientIdentity().GetID()

	reading := SensorReading{
		DocType:     "sensorReading",
		ID:          readingID,
		SensorID:    sensorID,
		Timestamp:   time.Now(),
		Data:        data,
		Quality:     quality,
		ProcessedAt: time.Now(),
		ValidatedBy: validatedBy,
	}

	readingJSON, err := json.Marshal(reading)
	if err != nil {
		return fmt.Errorf("erreur de sérialisation: %v", err)
	}

	// Mettre à jour le capteur
	sensor.LastReading = time.Now()
	sensorJSON, _ := json.Marshal(sensor)
	ctx.GetStub().PutState(sensorID, sensorJSON)

	// Émettre un événement si congestion détectée
	if occupancy > 80 {
		eventPayload := fmt.Sprintf(`{"sensorId":"%s","roadId":"%s","occupancy":%.2f,"alert":"HIGH_CONGESTION"}`,
			sensorID, sensor.RoadID, occupancy)
		ctx.GetStub().SetEvent("CongestionAlert", []byte(eventPayload))
	}

	return ctx.GetStub().PutState(readingID, readingJSON)
}

// RecordSpeedReading enregistre une lecture de radar de vitesse
func (c *SensorDataContract) RecordSpeedReading(ctx contractapi.TransactionContextInterface,
	readingID, sensorID string, currentSpeed, maxSpeed, minSpeed, averageSpeed float64,
	speedLimit, violationCount int) error {

	// Récupérer ou créer le capteur automatiquement
	sensor, err := c.getOrCreateSensor(ctx, sensorID, SensorTypeSpeed)
	if err != nil {
		return err
	}

	data := map[string]interface{}{
		"currentSpeed":   currentSpeed,
		"maxSpeed":       maxSpeed,
		"minSpeed":       minSpeed,
		"averageSpeed":   averageSpeed,
		"speedLimit":     speedLimit,
		"violationCount": violationCount,
	}

	quality := DataQualityHigh
	if currentSpeed < 0 || maxSpeed < minSpeed {
		quality = DataQualityInvalid
	}

	validatedBy, _ := ctx.GetClientIdentity().GetID()

	reading := SensorReading{
		DocType:     "sensorReading",
		ID:          readingID,
		SensorID:    sensorID,
		Timestamp:   time.Now(),
		Data:        data,
		Quality:     quality,
		ProcessedAt: time.Now(),
		ValidatedBy: validatedBy,
	}

	readingJSON, err := json.Marshal(reading)
	if err != nil {
		return fmt.Errorf("erreur de sérialisation: %v", err)
	}

	sensor.LastReading = time.Now()
	sensorJSON, _ := json.Marshal(sensor)
	ctx.GetStub().PutState(sensorID, sensorJSON)

	// Alerte si violations de vitesse
	if violationCount > 0 {
		eventPayload := fmt.Sprintf(`{"sensorId":"%s","roadId":"%s","violations":%d,"maxSpeed":%.2f}`,
			sensorID, sensor.RoadID, violationCount, maxSpeed)
		ctx.GetStub().SetEvent("SpeedViolationAlert", []byte(eventPayload))
	}

	return ctx.GetStub().PutState(readingID, readingJSON)
}

// RecordAirQualityReading enregistre une lecture de qualité de l'air
func (c *SensorDataContract) RecordAirQualityReading(ctx contractapi.TransactionContextInterface,
	readingID, sensorID string, pm25, pm10, no2, co, o3 float64, aqi int,
	temperature, humidity float64) error {

	// Récupérer ou créer le capteur automatiquement
	sensor, err := c.getOrCreateSensor(ctx, sensorID, SensorTypeAirQuality)
	if err != nil {
		return err
	}

	data := map[string]interface{}{
		"pm25":        pm25,
		"pm10":        pm10,
		"no2":         no2,
		"co":          co,
		"o3":          o3,
		"aqi":         aqi,
		"temperature": temperature,
		"humidity":    humidity,
	}

	quality := DataQualityHigh
	if pm25 < 0 || pm10 < 0 || aqi < 0 || aqi > 500 {
		quality = DataQualityInvalid
	}

	validatedBy, _ := ctx.GetClientIdentity().GetID()

	reading := SensorReading{
		DocType:     "sensorReading",
		ID:          readingID,
		SensorID:    sensorID,
		Timestamp:   time.Now(),
		Data:        data,
		Quality:     quality,
		ProcessedAt: time.Now(),
		ValidatedBy: validatedBy,
	}

	readingJSON, err := json.Marshal(reading)
	if err != nil {
		return fmt.Errorf("erreur de sérialisation: %v", err)
	}

	sensor.LastReading = time.Now()
	sensorJSON, _ := json.Marshal(sensor)
	ctx.GetStub().PutState(sensorID, sensorJSON)

	// Alerte si mauvaise qualité de l'air
	if aqi > 150 {
		severity := "warning"
		if aqi > 200 {
			severity = "critical"
		}
		eventPayload := fmt.Sprintf(`{"sensorId":"%s","aqi":%d,"severity":"%s"}`,
			sensorID, aqi, severity)
		ctx.GetStub().SetEvent("AirQualityAlert", []byte(eventPayload))
	}

	return ctx.GetStub().PutState(readingID, readingJSON)
}

// RecordWeatherReading enregistre une lecture météo
func (c *SensorDataContract) RecordWeatherReading(ctx contractapi.TransactionContextInterface,
	readingID, sensorID string, temperature, humidity, pressure, windSpeed float64,
	windDirection string, precipitation, visibility float64, roadCondition string) error {

	// Récupérer ou créer le capteur automatiquement
	sensor, err := c.getOrCreateSensor(ctx, sensorID, SensorTypeWeather)
	if err != nil {
		return err
	}

	data := map[string]interface{}{
		"temperature":   temperature,
		"humidity":      humidity,
		"pressure":      pressure,
		"windSpeed":     windSpeed,
		"windDirection": windDirection,
		"precipitation": precipitation,
		"visibility":    visibility,
		"roadCondition": roadCondition,
	}

	quality := DataQualityHigh

	validatedBy, _ := ctx.GetClientIdentity().GetID()

	reading := SensorReading{
		DocType:     "sensorReading",
		ID:          readingID,
		SensorID:    sensorID,
		Timestamp:   time.Now(),
		Data:        data,
		Quality:     quality,
		ProcessedAt: time.Now(),
		ValidatedBy: validatedBy,
	}

	readingJSON, err := json.Marshal(reading)
	if err != nil {
		return fmt.Errorf("erreur de sérialisation: %v", err)
	}

	sensor.LastReading = time.Now()
	sensorJSON, _ := json.Marshal(sensor)
	ctx.GetStub().PutState(sensorID, sensorJSON)

	// Alerte conditions dangereuses
	if roadCondition == "icy" || roadCondition == "flooded" || visibility < 1.0 {
		eventPayload := fmt.Sprintf(`{"sensorId":"%s","roadId":"%s","roadCondition":"%s","visibility":%.2f,"alert":"DANGEROUS_CONDITIONS"}`,
			sensorID, sensor.RoadID, roadCondition, visibility)
		ctx.GetStub().SetEvent("WeatherAlert", []byte(eventPayload))
	}

	return ctx.GetStub().PutState(readingID, readingJSON)
}

// GetReading récupère une lecture par son ID
func (c *SensorDataContract) GetReading(ctx contractapi.TransactionContextInterface,
	readingID string) (*SensorReading, error) {

	readingJSON, err := ctx.GetStub().GetState(readingID)
	if err != nil {
		return nil, fmt.Errorf("erreur de lecture du ledger: %v", err)
	}
	if readingJSON == nil {
		return nil, fmt.Errorf("la lecture %s n'existe pas", readingID)
	}

	var reading SensorReading
	err = json.Unmarshal(readingJSON, &reading)
	if err != nil {
		return nil, fmt.Errorf("erreur de désérialisation: %v", err)
	}

	return &reading, nil
}

// GetReadingsBySensor récupère les lectures d'un capteur
func (c *SensorDataContract) GetReadingsBySensor(ctx contractapi.TransactionContextInterface,
	sensorID string) ([]*SensorReading, error) {

	queryString := fmt.Sprintf(`{"selector":{"docType":"sensorReading","sensorId":"%s"}}`, sensorID)

	resultsIterator, err := ctx.GetStub().GetQueryResult(queryString)
	if err != nil {
		return nil, fmt.Errorf("erreur de requête: %v", err)
	}
	defer resultsIterator.Close()

	var readings []*SensorReading
	for resultsIterator.HasNext() {
		queryResult, err := resultsIterator.Next()
		if err != nil {
			return nil, err
		}

		var reading SensorReading
		err = json.Unmarshal(queryResult.Value, &reading)
		if err != nil {
			return nil, err
		}
		readings = append(readings, &reading)
	}

	return readings, nil
}

// GetReadingsByQuality récupère les lectures par qualité
func (c *SensorDataContract) GetReadingsByQuality(ctx contractapi.TransactionContextInterface,
	quality string) ([]*SensorReading, error) {

	queryString := fmt.Sprintf(`{"selector":{"docType":"sensorReading","quality":"%s"}}`, quality)

	resultsIterator, err := ctx.GetStub().GetQueryResult(queryString)
	if err != nil {
		return nil, fmt.Errorf("erreur de requête: %v", err)
	}
	defer resultsIterator.Close()

	var readings []*SensorReading
	for resultsIterator.HasNext() {
		queryResult, err := resultsIterator.Next()
		if err != nil {
			return nil, err
		}

		var reading SensorReading
		err = json.Unmarshal(queryResult.Value, &reading)
		if err != nil {
			return nil, err
		}
		readings = append(readings, &reading)
	}

	return readings, nil
}

// GetLatestReadingForSensor récupère la dernière lecture d'un capteur
func (c *SensorDataContract) GetLatestReadingForSensor(ctx contractapi.TransactionContextInterface,
	sensorID string) (*SensorReading, error) {

	queryString := fmt.Sprintf(`{"selector":{"docType":"sensorReading","sensorId":"%s"},"sort":[{"timestamp":"desc"}],"limit":1}`, sensorID)

	resultsIterator, err := ctx.GetStub().GetQueryResult(queryString)
	if err != nil {
		return nil, fmt.Errorf("erreur de requête: %v", err)
	}
	defer resultsIterator.Close()

	if resultsIterator.HasNext() {
		queryResult, err := resultsIterator.Next()
		if err != nil {
			return nil, err
		}

		var reading SensorReading
		err = json.Unmarshal(queryResult.Value, &reading)
		if err != nil {
			return nil, err
		}
		return &reading, nil
	}

	return nil, fmt.Errorf("aucune lecture trouvée pour le capteur %s", sensorID)
}

// BatchRecordReadings enregistre plusieurs lectures en lot
func (c *SensorDataContract) BatchRecordReadings(ctx contractapi.TransactionContextInterface,
	readingsJSON string) error {

	var readings []struct {
		ReadingID string                 `json:"readingId"`
		SensorID  string                 `json:"sensorId"`
		Data      map[string]interface{} `json:"data"`
		Quality   string                 `json:"quality"`
	}

	err := json.Unmarshal([]byte(readingsJSON), &readings)
	if err != nil {
		return fmt.Errorf("erreur de parsing des lectures: %v", err)
	}

	validatedBy, _ := ctx.GetClientIdentity().GetID()

	for _, r := range readings {
		// Vérifier que le capteur existe
		_, err := c.GetSensor(ctx, r.SensorID)
		if err != nil {
			continue // Skip invalid sensors
		}

		reading := SensorReading{
			DocType:     "sensorReading",
			ID:          r.ReadingID,
			SensorID:    r.SensorID,
			Timestamp:   time.Now(),
			Data:        r.Data,
			Quality:     DataQuality(r.Quality),
			ProcessedAt: time.Now(),
			ValidatedBy: validatedBy,
		}

		readingJSON, err := json.Marshal(reading)
		if err != nil {
			continue
		}

		ctx.GetStub().PutState(r.ReadingID, readingJSON)
	}

	// Émettre un événement
	eventPayload := fmt.Sprintf(`{"batchSize":%d,"processed":true}`, len(readings))
	ctx.GetStub().SetEvent("BatchReadingsRecorded", []byte(eventPayload))

	return nil
}

// DeleteOldReadings supprime les anciennes lectures (nettoyage)
func (c *SensorDataContract) DeleteOldReadings(ctx contractapi.TransactionContextInterface,
	sensorID string, beforeTimestamp string) error {

	queryString := fmt.Sprintf(`{"selector":{"docType":"sensorReading","sensorId":"%s"}}`, sensorID)

	resultsIterator, err := ctx.GetStub().GetQueryResult(queryString)
	if err != nil {
		return fmt.Errorf("erreur de requête: %v", err)
	}
	defer resultsIterator.Close()

	cutoffTime, err := time.Parse(time.RFC3339, beforeTimestamp)
	if err != nil {
		return fmt.Errorf("format de timestamp invalide: %v", err)
	}

	deletedCount := 0
	for resultsIterator.HasNext() {
		queryResult, err := resultsIterator.Next()
		if err != nil {
			return err
		}

		var reading SensorReading
		err = json.Unmarshal(queryResult.Value, &reading)
		if err != nil {
			continue
		}

		if reading.Timestamp.Before(cutoffTime) {
			ctx.GetStub().DelState(reading.ID)
			deletedCount++
		}
	}

	// Émettre un événement
	eventPayload := fmt.Sprintf(`{"sensorId":"%s","deletedCount":%d}`, sensorID, deletedCount)
	ctx.GetStub().SetEvent("OldReadingsDeleted", []byte(eventPayload))

	return nil
}
